name: test
channels:
  - defaults
dependencies:
  - alabaster=0.7.10
  - asn1crypto=0.24.0
  - babel=2.5.3
  - backcall=0.1.0
  - bleach=2.1.3
  - ca-certificates=2018.03.07
  - cartopy=0.16.0
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.2.2
  - cycler=0.10.0
  - dbus=1.13.2
  - decorator=4.3.0
  - docutils=0.14
  - entrypoints=0.2.3
  - expat=2.2.5
  - fontconfig=2.12.6
  - freetype=2.8
  - geos=3.6.2
  - glib=2.56.1
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.6
  - imagesize=1.0.0
  - ipykernel=4.8.2
  - ipython=6.3.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jedi=0.12.0
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libedit=3.1
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran-ng=7.2.0
  - libopenblas=0.2.20
  - libpng=1.6.34
  - libsodium=1.0.16
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.2.1
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.0
  - nomkl=1.0
  - notebook=5.4.1
  - numpy=1.14.2
  - numpydoc=0.8.0
  - olefile=0.45.1
  - openssl=1.0.2o
  - owslib=0.16.0
  - packaging=17.1
  - pandas=0.22.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.2.0
  - pcre=8.42
  - pexpect=4.5.0
  - pickleshare=0.7.4
  - pillow=5.1.0
  - pip=9.0.3
  - proj4=4.9.3
  - prompt_toolkit=1.0.15
  - ptyprocess=0.5.2
  - pycparser=2.18
  - pyepsg=0.3.2
  - pygments=2.2.0
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyqt=5.9.2
  - pyshp=1.2.12
  - pysocks=1.6.8
  - python=3.6.5
  - python-dateutil=2.7.2
  - pytz=2018.4
  - pyzmq=17.0.0
  - qt=5.9.5
  - qtconsole=4.3.1
  - readline=7.0
  - requests=2.18.4
  - scipy=1.0.1
  - send2trash=1.5.0
  - setuptools=39.0.1
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx=1.7.2
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - sqlite=3.23.1
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=5.0.2
  - traitlets=4.3.2
  - typing=3.6.4
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.0
  - widgetsnbextension=3.2.1
  - xz=5.2.3
  - zeromq=4.2.5
  - zlib=1.2.11
  - pip:
    - click==6.7
    - click-plugins==1.0.3
    - cligj==0.4.0
    - descartes==1.1.0
    - fiona==1.7.11.post1
    - geopandas==0.3.0
    - munch==2.3.1
